# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1424, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 30, 531, 191))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(430, 220, 101, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(120, 250, 751, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(330, 0, 301, 31))
        self.lblTtitulo.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo.setObjectName("lblTtitulo")
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(50, 80, 161, 31))
        self.lblTtitulo_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(100, 250, 181, 71))
        self.lblTtitulo2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo2.setText("")
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))
        self.lblTtitulo2.setObjectName("lblTtitulo2")
        self.lblTtitulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_2.setGeometry(QtCore.QRect(910, 10, 301, 31))
        self.lblTtitulo_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_2.setObjectName("lblTtitulo_2")
        self.lblTtitulo_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_4.setGeometry(QtCore.QRect(890, 240, 301, 31))
        self.lblTtitulo_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_4.setObjectName("lblTtitulo_4")
        self.lblTtitulo_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_5.setGeometry(QtCore.QRect(880, 470, 301, 31))
        self.lblTtitulo_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_5.setObjectName("lblTtitulo_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(840, 40, 541, 192))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(880, 270, 531, 192))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(4)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(880, 510, 521, 192))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Alejandro Arango Mejìa"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos>>"))
        self.lblTtitulo_2.setText(_translate("MainWindow", "Matriz de Adyacencia"))
        self.lblTtitulo_4.setText(_translate("MainWindow", "Matriz cuando k=2"))
        self.lblTtitulo_5.setText(_translate("MainWindow", "Matriz cuando k=3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
